---
title: "Conditional QTE/PTE Analysis for CD4 Outcome"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# AIPW-CPM-icdf

read the data

```{r}
rm(list = ls())
load("data_model_cd4_YA_synthetic.RData")
source("Helper_functions.R")
```

model fitting

```{r, warning=F, message=F}

library(rms)
library(dplyr)

formA = A ~ rcs(age, 4) + sex + site + route_infection + prior_aids +
  rcs(months_toCD4measure, 4) + cd4_baseline_tran + calendar_year+
  singledl_rna_baseline_v_tran


formY1 = Y ~ age + sex + site + route_infection + prior_aids + 
              calendar_year +
              rcs(cd4_baseline_tran,4) +
              rcs(singledl_rna_baseline_v_tran, 4) +
              rcs(months_toCD4measure,4)

formY0 = Y ~ age + sex + site + route_infection + prior_aids + 
              calendar_year +
              rcs(cd4_baseline_tran,4) +
              rcs(singledl_rna_baseline_v_tran, 4) +
              rcs(months_toCD4measure,4)

formY = Y ~ A + age + sex + site + route_infection + prior_aids + 
              calendar_year +
              rcs(cd4_baseline_tran,4) +
              rcs(singledl_rna_baseline_v_tran, 4) +
              rcs(months_toCD4measure,4)

data_cpm = as.data.frame(data_model)
data_cpm1 = data_cpm %>% filter(A == 1)
data_cpm0 = data_cpm %>% filter(A == 0)

# OR 
dd = datadist(data_cpm);options(datadist = "dd")
g = orm(formY, family = "logistic", x=T, y = T,data = data_cpm)
dd = datadist(data_cpm1); options(datadist = "dd")
g1 = orm(formY1, family = "logistic", x= T, y =T, data = data_cpm1)
dd = datadist(data_cpm0);options(datadist = "dd")
g0 = orm(formY0, family = "logistic", x= T, y =T,data = data_cpm0)

alpha1_hat = -g1$coefficients[1:(length(g1$yunique) - 1)]
alpha0_hat = -g0$coefficients[1:(length(g0$yunique) - 1)]

  
  # PS model
  ps_fit= glm(formA, data = data_cpm, family = binomial("logit"))
  pi1 = predict(ps_fit, type = "response", newdata = data_cpm)
  pi0=  1- predict(ps_fit, type = "response", newdata = data_cpm)
  
#pi1 = pmin(pmax(pi1, 0.1), 0.9); pi0 = pmin(pmax(pi0, 0.1), 0.9)

  IA1 = as.numeric(data_cpm$A == 1); IA0 = as.numeric(data_cpm$A == 0)
  weight1 = IA1 / pi1 ; weight0 = IA0 / pi0                     
 

# DR 
n = nrow(data_cpm);n1 = nrow(data_cpm1);n0 = nrow(data_cpm0)
DR1  = matrix(NA, n, n);DR0  = matrix(NA, n, n)


  
  for (i in seq_len(n)) {
    y_star = data_cpm$Y[i]
    
    # A = 0
    IY1 = as.numeric(data_cpm$Y <= y_star)
   g1_vals= calc_g_twomodels(data_cpm,y_star, g = g1, all_g = g, alpha_hat = alpha1_hat, tolerance = 1e-4)
    DR1[,i] = (IA1 / pi1) * (IY1 - g1_vals$g_y) + g1_vals$g_y
      
    
    # A = 1
    IY0 = as.numeric(data_cpm$Y <= y_star)
     g0_vals= calc_g_twomodels(data_cpm,y_star, g = g0, all_g = g, alpha_hat = alpha0_hat, tolerance = 1e-4)
    DR0[,i] = (IA0 / pi0 )* (IY0 - g0_vals$g_y) + g0_vals$g_y

  }
  
ord1 = order(data_cpm$Y);Ygrid1 = data_cpm$Y[ord1]  
ord0 = order(data_cpm$Y);Ygrid0 = data_cpm$Y[ord0]  
c_cdf1 = DR1[,ord1] ;  c_cdf0 = DR0[,ord0]   


```

## Conditional Analysis by Sex

```{r, warning=F, message=F}

M_idx = which(data_cpm$sex == 1); F_idx = which(data_cpm$sex == 0)

OR1_M_cdf = cummax(pmin(pmax(colMeans(c_cdf1[M_idx, , drop = FALSE]), 0), 1))
OR1_F_cdf = cummax(pmin(pmax(colMeans(c_cdf1[F_idx, , drop = FALSE]), 0), 1))

OR0_M_cdf = cummax(pmin(pmax(colMeans(c_cdf0[M_idx, , drop = FALSE]), 0), 1))
OR0_F_cdf = cummax(pmin(pmax(colMeans(c_cdf0[F_idx, , drop = FALSE]), 0), 1))


# monotone increasing
all(diff(OR1_M_cdf) >= 0)
all(diff(OR1_F_cdf) >= 0)
all(diff(OR0_M_cdf) >= 0)
all(diff(OR0_F_cdf) >= 0)

# within [0, 1]
all(OR1_M_cdf >= 0 & OR1_M_cdf <= 1)
all(OR1_F_cdf >= 0 & OR1_F_cdf <= 1)
all(OR0_M_cdf >= 0 & OR0_M_cdf <= 1)
all(OR0_F_cdf >= 0 & OR0_F_cdf <= 1)
```

### QTE figure

```{r, warning=F, message=F}
##  QTE(p) 
p_grid = seq(0.02, 0.96, by = 0.02)


res = lapply(p_grid, function(p){
  q1_F = quantile_inversion(Ygrid1,OR1_F_cdf, p)
  q0_F = quantile_inversion(Ygrid0,OR0_F_cdf, p)

  q1_M = quantile_inversion(Ygrid1,OR1_M_cdf, p)
  q0_M = quantile_inversion(Ygrid0,OR0_M_cdf, p)

  data.frame(
    p_star = p,
    q1_F = q1_F, q0_F = q0_F, QTE_F = q1_F - q0_F,
    q1_M = q1_M, q0_M = q0_M, QTE_M = q1_M - q0_M
  )
})

qte_table = do.call(rbind, res)

###############################################################
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)


## Panel 1: quantile functions (q1/q0) with two models (F/M)
q_long = qte_table %>%
  dplyr::select(p_star, q1_F, q0_F, q1_M, q0_M) %>%
  pivot_longer(
    cols = -p_star,
    names_to = c("curve", "model"),
    names_pattern = "(q[01])_(F|M)",
    values_to = "value"
  ) %>%
  mutate(
    curve = recode(curve, q1 = "q1 (A=1)", q0 = "q0 (A=0)"),
    model = recode(model, F = "Model F", M = "Model M")
  )

p_q = ggplot(q_long, aes(x = p_star, y = value, color = curve, linetype = model)) +
  geom_line(linewidth = 1) +
  scale_color_manual(values = c("q1 (A=1)" = "red", "q0 (A=0)" = "green")) +
  theme_bw(base_size = 13) +
  labs(x = "Quantile level p", y = "Quantile", color = NULL, linetype = NULL,
       title = "Separate models") +
  theme(legend.position = "top")

## Panel 2: QTE curves with two models (F/M)
qte_long = qte_table %>%
  dplyr::select(p_star, QTE_F, QTE_M) %>%
  pivot_longer(
    cols = -p_star,
    names_to = "model",
    values_to = "QTE",
    names_pattern = "QTE_(F|M)"
  ) %>%
  mutate(model = recode(model, F = "Model F", M = "Model M"))

p_qte = ggplot(qte_long, aes(x = p_star, y = QTE, linetype = model)) +
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.8, color = "red") +
  geom_line(linewidth = 1) +
  theme_bw(base_size = 13) +
  labs(x = "Quantile level p", y = "CQTE",
       linetype = NULL, title = "CQTE AIPW-CPM-icdf ") +
  theme(legend.position = "top")

p_q | p_qte

```

### PTE figure

```{r, warning=F, message=F}


## PTE table 
xout = seq(10, 2050, by = 5)
P1_F = approx(x = Ygrid1, y = OR1_F_cdf, xout = xout, rule = 2)$y
P0_F = approx(x = Ygrid0, y = OR0_F_cdf, xout = xout, rule = 2)$y

P1_M = approx(x = Ygrid1, y = OR1_M_cdf, xout = xout, rule = 2)$y
P0_M = approx(x = Ygrid0, y = OR0_M_cdf, xout = xout, rule = 2)$y

pte_table = data.frame(
  y = xout,
  P1_F = P1_F, P0_F = P0_F, PTE_F = P1_F - P0_F,
  P1_M = P1_M, P0_M = P0_M, PTE_M = P1_M - P0_M
)



###############################################################
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)


left_long = pte_table %>%
  dplyr::select(y, P1_F, P0_F, P1_M, P0_M) %>%
  pivot_longer(
    cols = -y,
    names_to = c("curve", "model"),
    names_pattern = "(P1|P0)_(F|M)",
    values_to = "value"
  ) %>%
  mutate(
    curve = recode(curve,
                   P0 = "q0 (A=0)",
                   P1 = "q1 (A=1)"),
    model = recode(model,
                   F = "Model F",
                   M = "Model M")
  )

p_left = ggplot(
  left_long,
  aes(x = y, y = value,
      color = curve,
      linetype = model)
) +
  geom_line(linewidth = 1) +
  scale_color_manual(values = c(
    "q0 (A=0)" = "green",
    "q1 (A=1)" = "red"
  )) +
  scale_linetype_manual(values = c(
    "Model F" = "solid",
    "Model M" = "dashed"
  )) +
  theme_bw(base_size = 13) +
  theme(
    legend.position = "top"   
  ) +
  labs(
    title = "Separate models",
    x = "Y",
    y = "conditional probability",
    color = NULL,
    linetype = NULL
  )


pte_long = pte_table %>%
  dplyr::select(y, PTE_F, PTE_M) %>%
  pivot_longer(
    cols = -y,
    names_to = "model",
    values_to = "pte"
  ) %>%
  mutate(model = recode(model,
                        PTE_F = "Model F",
                        PTE_M = "Model M"))

p_right = ggplot(
  pte_long,
  aes(x = y, y = pte,
      linetype = model)
) +
  geom_line(linewidth = 1, color = "black") +
  geom_hline(yintercept = 0,
             color = "red",
             linetype = "dashed") +
  scale_linetype_manual(values = c(
    "Model F" = "solid",
    "Model M" = "dashed"
  )) +
  theme_bw(base_size = 13) +
  theme(
    legend.position = "none"   
  ) +
  labs(
    title = "CPTE AIPW-CPM-icdf" ,
    x = "Y",
    y = "PTE"
  )


p_left + p_right

```

# AIPW-CPM

read data

```{r}
rm(list = ls())
load("data_model_cd4_YA_synthetic.RData")
source("Helper_functions.R")
```

model fitting

```{r, warning=F, message=F}

library(rms)
library(dplyr)

formA = A ~ rcs(age, 4) + sex + site + route_infection + prior_aids +
  rcs(months_toCD4measure, 4) + cd4_baseline_tran + calendar_year+
  singledl_rna_baseline_v_tran


formY1 = Y ~ age + sex + site + route_infection + prior_aids + 
              calendar_year +
              rcs(cd4_baseline_tran,4) +
              rcs(singledl_rna_baseline_v_tran, 4) +
              rcs(months_toCD4measure,4)

formY0 = Y ~ age + sex + site + route_infection + prior_aids + 
              calendar_year +
              rcs(cd4_baseline_tran,4) +
              rcs(singledl_rna_baseline_v_tran, 4) +
              rcs(months_toCD4measure,4)

formY = Y ~ A + age + sex + site + route_infection + prior_aids + calendar_year + rcs(cd4_baseline_tran,4) + rcs(singledl_rna_baseline_v_tran, 4) + rcs(months_toCD4measure,4)

data_cpm = as.data.frame(data_model)
data_cpm1 = data_cpm %>% filter(A == 1)
data_cpm0 = data_cpm %>% filter(A == 0)

  # PS model
  ps_fit= glm(formA, data = data_cpm, family = binomial("logit"))
  pi1 = predict(ps_fit, type = "response", newdata = data_cpm)
  pi0=  1- predict(ps_fit, type = "response", newdata = data_cpm)
  
#pi1 = pmin(pmax(pi1, 0.1), 0.9); pi0 = pmin(pmax(pi0, 0.1), 0.9)

  IA1 = as.numeric(data_cpm$A == 1); IA0 = as.numeric(data_cpm$A == 0)
  weight1 = IA1 / pi1 ; weight0 = IA0 / pi0  
  

# OR 
dd = datadist(data_cpm);options(datadist = "dd")
g = orm(formY, family = "logistic", x=T, y = T,data = data_cpm)
dd = datadist(data_cpm1); options(datadist = "dd")
g1 = orm(formY1, family = "logistic", x= T, y =T, data = data_cpm1)
dd = datadist(data_cpm0);options(datadist = "dd")
g0 = orm(formY0, family = "logistic", x= T, y =T,data = data_cpm0)

alpha1_hat = -g1$coefficients[1:(length(g1$yunique) - 1)]
alpha0_hat = -g0$coefficients[1:(length(g0$yunique) - 1)]
  
n = nrow(data_cpm);OR1  = matrix(NA, n, n);OR0  = matrix(NA, n, n)

                      
for (i in 1:n) {
  y_star = data_cpm$Y[i]
  
  g1_vals= calc_g_twomodels(data_cpm,y_star, g = g1, all_g = g, alpha_hat = alpha1_hat, tolerance = 1e-4)
  g0_vals= calc_g_twomodels(data_cpm,y_star, g = g0, all_g = g, alpha_hat = alpha0_hat, tolerance = 1e-4)
  
  OR1[,i] = g1_vals$g_y;OR0[,i] = g0_vals$g_y
}

ord1 = order(data_cpm$Y);Ygrid1 = data_cpm$Y[ord1]  
ord0 = order(data_cpm$Y);Ygrid0 = data_cpm$Y[ord0]  

c_cdf1 = OR1[,ord1] ;  c_cdf0 = OR0[,ord0]   



```

## Conditional Analysis by Sex

```{r, warning=F, message=F}

M_idx = which(data_cpm$sex == 1); F_idx = which(data_cpm$sex == 0)

DR1_F  = function(q, A = 1) {

  Yg = data_cpm$Y;n = length(Yg); Yg = Yg[order(Yg)]
  if (q <  Yg[1])  return(c(DR1_F= 0))
  if (q >= Yg[n]) return(c(DR1_F = 1))

  IY1 = as.numeric(data_cpm$Y <= q)
  j = findInterval(q, Yg, rightmost.closed = TRUE)


  DR1_F = mean( (IA1[F_idx] / pi1[F_idx]) * (IY1[F_idx] - c_cdf1[F_idx, j]) + c_cdf1[F_idx, j] )

  DR1_F
}



DR1_M = function(q, A = 1) {

  Yg = data_cpm$Y;n = length(Yg); Yg = Yg[order(Yg)]

  if (q <  Yg[1])  return(c(DR1_M= 0))
  if (q >= Yg[n]) return(c(DR1_M= 1))

  IY1 = as.numeric(data_cpm$Y <= q)

  j = findInterval(q, Yg, rightmost.closed = TRUE)
  j = max(1, min(j, ncol(c_cdf1)))

  DR1_M = mean((IA1[M_idx] / pi1[M_idx]) * (IY1[M_idx] - c_cdf1[M_idx, j]) + c_cdf1[M_idx, j])

  DR1_M
}


DR0_F = function(q, A = 0) {

  Yg = data_cpm$Y;n = length(Yg); Yg = Yg[order(Yg)]

  if (q < Yg[1])        return(0)
  if (q >= Yg[n])        return(1)

  IY0 = as.numeric(data_cpm$Y <= q)
  j = findInterval(q, Yg, rightmost.closed = TRUE)
  j = max(1, min(j, ncol(c_cdf0)))

  DR0_F = mean((IA0[F_idx] / pi0[F_idx]) * (IY0[F_idx] - c_cdf0[F_idx, j]) + c_cdf0[F_idx, j])

DR0_F
}

DR0_M = function(q, A = 0) {

  Yg = data_cpm$Y;n = length(Yg); Yg = Yg[order(Yg)]

  if (q < Yg[1])        return(0)
  if (q >= Yg[n])        return(1)

  IY0 = as.numeric(data_cpm$Y <= q)
  j = findInterval(q, Yg, rightmost.closed = TRUE)
  j = max(1, min(j, ncol(c_cdf0)))

  DR0_M = mean((IA0[M_idx] / pi0[M_idx]) * (IY0[M_idx] - c_cdf0[M_idx, j]) + c_cdf0[M_idx, j])

  DR0_M
}


```

### QTE figure

```{r, warning=F, message=F}


## qte table
p_grid = seq(0.02, 0.96, by = 0.02)

Yg = data_cpm$Y;n = length(Yg); Yg = Yg[order(Yg)]

res_list = lapply(p_grid, function(p) {
  
  q1_F= uniroot(function(q) DR1_F(q, 1) - p,
                interval = c(Yg[1], Yg[length(Yg)]),
                tol = 1e-8)$root
  
  q0_F = uniroot(function(q) DR0_F(q, 0) - p,
                interval = c(Yg[1], Yg[length(Yg)]),
                tol = 1e-8)$root
  
  q1_M = uniroot(function(q) DR1_M(q, 1) - p,
                interval = c(Yg[1], Yg[length(Yg)]),
                tol = 1e-8)$root
  
  q0_M = uniroot(function(q) DR0_M(q, 0) - p,
                interval = c(Yg[1], Yg[length(Yg)]),
                tol = 1e-8)$root
  
  data.frame(
    p_star   = p,
    q1_F  = q1_F, q0_F =  q0_F, QTE_F = q1_F - q0_F,
    q1_M  = q1_M, q0_M =  q0_M, QTE_M = q1_M - q0_M
  )
})


qte_table = do.call(rbind, res_list)

sapply(qte_table[, c("q1_F", "q0_F", "q1_M", "q0_M")], function(x) all(diff(x) >= 0))




###############################################################
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)


## Panel 1: quantile functions (q1/q0) with two models (F/M)
q_long = qte_table %>%
  dplyr::select(p_star, q1_F, q0_F, q1_M, q0_M) %>%
  pivot_longer(
    cols = -p_star,
    names_to = c("curve", "model"),
    names_pattern = "(q[01])_(F|M)",
    values_to = "value"
  ) %>%
  mutate(
    curve = recode(curve, q1 = "q1 (A=1)", q0 = "q0 (A=0)"),
    model = recode(model, F = "Model F", M = "Model M")
  )

p_q = ggplot(q_long, aes(x = p_star, y = value, color = curve, linetype = model)) +
  geom_line(linewidth = 1) +
  scale_color_manual(values = c("q1 (A=1)" = "red", "q0 (A=0)" = "green")) +
  theme_bw(base_size = 13) +
  labs(x = "Quantile level p", y = "Quantile", color = NULL, linetype = NULL,
       title = "Separate models") +
  theme(legend.position = "top")

## Panel 2: QTE curves with two models (F/M)
qte_long = qte_table %>%
  dplyr::select(p_star, QTE_F, QTE_M) %>%
  pivot_longer(
    cols = -p_star,
    names_to = "model",
    values_to = "QTE",
    names_pattern = "QTE_(F|M)"
  ) %>%
  mutate(model = recode(model, F = "Model F", M = "Model M"))

p_qte = ggplot(qte_long, aes(x = p_star, y = QTE, linetype = model)) +
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.8, color = "red") +
  geom_line(linewidth = 1) +
  theme_bw(base_size = 13) +
  labs(x = "Quantile level p", y = "CQTE",
       linetype = NULL, title = "CQTE- AIPW-CPM ") +
  theme(legend.position = "top")

p_q | p_qte

```
