---
title: "Marginal QTE/PTE Analysis for Viral Load Outcome"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# AIPW-CPM-icdf

read the data

```{r}
rm(list = ls())
load("data_model_VL_YA_synthetic.RData")
source("Helper_functions.R")
```

model fitting

```{r, warning=F, message=F}

library(rms)
library(dplyr)

formA <- A ~ 
  rcs(age, 4) +
  sex +
  site +
  route_infection +
  prior_aids +
  rcs(months_toVLmeasure, 4) +
  cd4_baseline_tran +
  calendar_year +
  singledl_rna_baseline_v_tran


formY1 = Y ~ age + sex + site + route_infection + prior_aids +
              calendar_year+
              rcs(cd4_baseline_tran,4) +
              rcs(singledl_rna_baseline_v_tran,4) +
              rcs(months_toVLmeasure, 4)

formY0 = Y ~ age + sex + site + route_infection + prior_aids +
              calendar_year+
              rcs(cd4_baseline_tran,4) +
              rcs(singledl_rna_baseline_v_tran,4) +
              rcs(months_toVLmeasure, 4)

formY = Y ~ A + age + sex + site + route_infection + prior_aids + 
              calendar_year +
              rcs(cd4_baseline_tran,4) +
              rcs(singledl_rna_baseline_v_tran, 4) +
              rcs(months_toVLmeasure, 4)

data_cpm = as.data.frame(data_model)
data_cpm1 = data_cpm %>% filter(A == 1)
data_cpm0 = data_cpm %>% filter(A == 0)

# OR 
dd = datadist(data_cpm);options(datadist = "dd")
g = orm(formY, family = "logistic", x=T, y = T,data = data_cpm)
dd = datadist(data_cpm1); options(datadist = "dd")
g1 = orm(formY1, family = "logistic", x= T, y =T, data = data_cpm1)
dd = datadist(data_cpm0);options(datadist = "dd")
g0 = orm(formY0, family = "logistic", x= T, y =T,data = data_cpm0)

alpha1_hat = -g1$coefficients[1:(length(g1$yunique) - 1)]
alpha0_hat = -g0$coefficients[1:(length(g0$yunique) - 1)]

  
  # PS model
  ps_fit= glm(formA, data = data_cpm, family = binomial("logit"))
  pi1 = predict(ps_fit, type = "response", newdata = data_cpm)
  pi0=  1- predict(ps_fit, type = "response", newdata = data_cpm)
  
pi1 = pmin(pmax(pi1, 0.1), 0.9); pi0 = pmin(pmax(pi0, 0.1), 0.9)

  IA1 = as.numeric(data_cpm$A == 1); IA0 = as.numeric(data_cpm$A == 0)
  weight1 = IA1 / pi1 ; weight0 = IA0 / pi0                        
 

# DR 
n = nrow(data_cpm);n1 = nrow(data_cpm1);n0 = nrow(data_cpm0)
F1_ipw = numeric(n); F0_ipw = numeric(n)
DR1  = numeric(n);DR0  = numeric(n)


  
  for (i in seq_len(n)) {
    y1_star = data_cpm1$Y[i]; y0_star = data_cpm0$Y[i];y_star = data_cpm$Y[i]
    
    # A = 0
    IY1 = as.numeric(data_cpm$Y <= y_star)
    F1_ipw[i] =sum(weight1 * IY1) / sum(weight1) 
     #F1_ipw[i] = mean(weight1 * IY1) 
   g1_vals= calc_g_twomodels(data_cpm,y_star, g = g1, all_g = g, alpha_hat = alpha1_hat, tolerance = 1e-4)
    DR1[i] = mean(IA1 / pi1 * (IY1 - g1_vals$g_y) + g1_vals$g_y)
      
    
    # A = 1
    IY0 = as.numeric(data_cpm$Y <= y_star)
    F0_ipw[i] = sum(weight0 * IY0) / sum(weight0) 
     #F0_ipw[i] = mean(weight0 * IY0) 
     g0_vals= calc_g_twomodels(data_cpm,y_star, g = g0, all_g = g, alpha_hat = alpha0_hat, tolerance = 1e-4)
    DR0[i] = mean(IA0 / pi0 * (IY0 - g0_vals$g_y) + g0_vals$g_y)

    
      
 

  }
  

ord1 = order(DR1); ord0 = order(DR0)    
Ygrid1 = data_cpm$Y[ord1]; Ygrid0 = data_cpm$Y[ord0]  
DR1_sorted = DR1[ord1]; DR0_sorted = DR0[ord0] 
# summary(DR1_sorted);summary(DR0_sorted)
# summary(F1_ipw);summary(F0_ipw)
  ##########################################################
##  QTE(p) 
p_grid = seq(0.02, 0.96, by = 0.02)

q1_vec = sapply(p_grid, function(p) quantile_inversion(Ygrid1, DR1_sorted, p))
q0_vec = sapply(p_grid, function(p) quantile_inversion(Ygrid0, DR0_sorted, p))

qte_table = data.frame(
  p   = p_grid,
  q1  = as.numeric(q1_vec),
  q0  = as.numeric(q0_vec),
  QTE = as.numeric(q1_vec - q0_vec)
)


## PTE table 
xout = seq(40, 2000, by = 10)

PY1 = approx(x = Ygrid1, y = DR1_sorted , xout = xout, rule = 2)$y
PY0 = approx(x = Ygrid0, y = DR0_sorted  , xout = xout, rule = 2)$y

PTE = PY1 - PY0

pte_table = data.frame(
  Y   = xout,
  PY1 = PY1,
  PY0 = PY0,
  PTE = PTE
)

```

## PTE figure

```{r}

library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)


## Plot 1: PTE vs Y
p_pte = ggplot(pte_table, aes(x = Y, y = PTE)) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_line(linewidth = 1) +
  theme_bw(base_size = 13) +
  labs(
    x = "Y",
    y = "PTE",
    title = "MPTE AIPW_CPM_icdf "
  )


## Plot 2: PY1 & PY0 vs Y
py_long = pte_table %>%
  pivot_longer(cols = c(PY1, PY0), names_to = "curve", values_to = "value")

p_py = ggplot(py_long, aes(x = Y, y = value, color = curve)) +
  geom_line(linewidth = 1) +
  theme_bw(base_size = 13) +
  labs(
    x = "Y",
    y = "P(Y<=Y | A=a)",
    color = NULL,
    title = "Separate models "
  ) +
  theme(legend.position = "top")


p_py |p_pte

```

## QTE figure

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)

# qte_table: p, q1, q0, QTE


q_long = qte_table %>%
  select(p, q1, q0) %>%
  pivot_longer(cols = c(q1, q0), names_to = "curve", values_to = "value") %>%
  mutate(curve = recode(curve, q1 = "q1 (A=1)", q0 = "q0 (A=0)"))

p_q = ggplot(q_long, aes(x = p, y = value, color = curve)) +
  geom_line(linewidth = 1) +
  scale_color_manual(values = c("q1 (A=1)" = "red", "q0 (A=0)" = "green")) +
  theme_bw(base_size = 13) +
  labs(x = "Quantile level p", y = "Quantile", color = NULL,
       title = "Separate models") +
  theme(legend.position = "top")

# Plot 2: QTE
p_qte = ggplot(qte_table, aes(x = p, y = QTE)) +
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.8, color = "red") +
  geom_line(linewidth = 1) +
  theme_bw(base_size = 13) +
  labs(x = "Quantile level p", y = "MQTE(p)",
       title = "MQTE AIPW_CPM_icdf") 


p_q | p_qte

```

# AIPW-CPM

read data

```{r}
rm(list = ls())
load("data_model_VL_YA_synthetic.RData")
source("Helper_functions.R")
```

model fitting

```{r, warning=F, message=F}

library(rms)
library(dplyr)

formA = A ~ 
  rcs(age, 4) +
  sex +
  site +
  route_infection +
  prior_aids +
  rcs(months_toVLmeasure, 4) +
  cd4_baseline_tran +
  calendar_year +
  singledl_rna_baseline_v_tran


formY1 = Y ~ age + sex + site + route_infection + prior_aids +
              calendar_year+
              rcs(cd4_baseline_tran,4) +
              rcs(singledl_rna_baseline_v_tran,4) +
              rcs(months_toVLmeasure, 4)

formY0 = Y ~ age + sex + site + route_infection + prior_aids +
              calendar_year+
              rcs(cd4_baseline_tran,4) +
              rcs(singledl_rna_baseline_v_tran,4) +
              rcs(months_toVLmeasure, 4)

formY = Y ~ A + age + sex + site + route_infection + prior_aids + 
              calendar_year +
              rcs(cd4_baseline_tran,4) +
              rcs(singledl_rna_baseline_v_tran, 4) +
              rcs(months_toVLmeasure, 4)

data_cpm = as.data.frame(data_model)
data_cpm1 = data_cpm %>% filter(A == 1)
data_cpm0 = data_cpm %>% filter(A == 0)

  # PS model
  ps_fit= glm(formA, data = data_cpm, family = binomial("logit"))
  pi1 = predict(ps_fit, type = "response", newdata = data_cpm)
  pi0=  1- predict(ps_fit, type = "response", newdata = data_cpm)
  
#pi1 = pmin(pmax(pi1, 0.1), 0.9); pi0 = pmin(pmax(pi0, 0.1), 0.9)

  IA1 = as.numeric(data_cpm$A == 1); IA0 = as.numeric(data_cpm$A == 0)
  weight1 = IA1 / pi1 ; weight0 = IA0 / pi0  
  

# OR 
dd = datadist(data_cpm);options(datadist = "dd")
g = orm(formY, family = "logistic", x=T, y = T,data = data_cpm)
dd = datadist(data_cpm1); options(datadist = "dd")
g1 = orm(formY1, family = "logistic", x= T, y =T, data = data_cpm1)
dd = datadist(data_cpm0);options(datadist = "dd")
g0 = orm(formY0, family = "logistic", x= T, y =T,data = data_cpm0)

alpha1_hat = -g1$coefficients[1:(length(g1$yunique) - 1)]
alpha0_hat = -g0$coefficients[1:(length(g0$yunique) - 1)]
  
n = nrow(data_cpm);OR1  = matrix(NA, n, n);OR0  = matrix(NA, n, n)

                      
for (i in 1:n) {
  y_star = data_cpm$Y[i]
  
  g1_vals= calc_g_twomodels(data_cpm,y_star, g = g1, all_g = g, alpha_hat = alpha1_hat, tolerance = 1e-4)
  g0_vals= calc_g_twomodels(data_cpm,y_star, g = g0, all_g = g, alpha_hat = alpha0_hat, tolerance = 1e-4)
  
  OR1[,i] = g1_vals$g_y;OR0[,i] = g0_vals$g_y
}

ord1 = order(data_cpm$Y);Ygrid1 = data_cpm$Y[ord1]  
ord0 = order(data_cpm$Y);Ygrid0 = data_cpm$Y[ord0]  

c_cdf1 = OR1[,ord1] ;  c_cdf0 = OR0[,ord0]   






F_DR1 = function(q, A = 1) {
  
  if (q < Ygrid1[1])        return(0)
  if (q >= Ygrid1[n])        return(1)
  
  IY1 = as.numeric(data_cpm$Y <= q)
  j= findInterval(q, Ygrid1, rightmost.closed = TRUE)
  DR1 = mean(IA1 / pi1 * (IY1 - c_cdf1[, j] ) + c_cdf1[, j] )
 
  DR1
}

F_DR0 = function(q, A = 0) {
  
  if (q < Ygrid0[1])        return(0)
  if (q >= Ygrid0[n])        return(1)
  
  IY0 = as.numeric(data_cpm$Y <= q)
  j= findInterval(q, Ygrid0, rightmost.closed = TRUE)
  DR0 = mean(IA0 / pi0 * (IY0 - c_cdf0[, j] ) + c_cdf0[, j] )
  DR0
}



#######################################################
## qte table
p_grid = seq(0.86, 0.96, by = 0.02)


res_list = lapply(p_grid, function(p) {
  
  q1 = uniroot(function(q) F_DR1(q, 1) - p,
                interval = c(Ygrid1[1], Ygrid1[length(Ygrid1)]),
                tol = 1e-8)$root
  
  q0 = uniroot(function(q) F_DR0(q, 0) - p,
                interval = c(Ygrid0[1], Ygrid0[length(Ygrid0)]),
                tol = 1e-8)$root
  
  data.frame(
    p   = p,
    q1  = q1,
    q0  = q0,
    QTE = q1 - q0
  )
})


qte_table = do.call(rbind, res_list)




```

## QTE figure

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)

# qte_table: p, q1, q0, QTE


q_long = qte_table %>%
  select(p, q1, q0) %>%
  pivot_longer(cols = c(q1, q0), names_to = "curve", values_to = "value") %>%
  mutate(curve = recode(curve, q1 = "q1 (A=1)", q0 = "q0 (A=0)"))

p_q = ggplot(q_long, aes(x = p, y = value, color = curve)) +
  geom_line(linewidth = 1) +
  scale_color_manual(values = c("q1 (A=1)" = "red", "q0 (A=0)" = "green")) +
  theme_bw(base_size = 13) +
  labs(x = "Quantile level p", y = "Quantile", color = NULL,
       title = "Separate models") +
  theme(legend.position = "top")

# Plot 2: QTE
p_qte = ggplot(qte_table, aes(x = p, y = QTE)) +
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.8, color = "red") +
  geom_line(linewidth = 1) +
  theme_bw(base_size = 13) +
  labs(x = "Quantile level p", y = "MQTE(p)",
       title = "MQTE AIPW_CPM") 


p_q | p_qte

```
